---
terminal:
  # Whether background should support non-opaque color. It must be set before
  # executing open() method and can't be changed later without excuting it again.
  # Warning: Enabling this option can reduce performances somewhat.
  # Valid values: true, false
  allowTransparency: true

  # A data uri of the sound to use for the bell (needs bellStyle = 'sound').
  bellSound: ""

  # The type of the bell notification the terminal will use.
  # Valid values: none, sound
  bellStyle: none

  # When enabled the cursor will be set to the beginning of the next line
  # with every new line. This equivalent to sending '\r\n' for each '\n'.
  # Normally the termios settings of the underlying PTY deals with the
  # translation of '\n' to '\r\n' and this setting should not be used. If you
  # deal with data from a non-PTY related source, this settings might be
  # useful.
  # Valid values: true, false
  convertEol: false

  # Whether the cursor blinks.
  # Valid values: true, false
  cursorBlink: true

  # The style of the cursor.
  # Valid values: block, underline, bar
  cursorStyle: block

  # Whether to draw bold text in bright colors. The default is true.
  # Valid values: true, false
  drawBoldTextInBrightColors: true

  # The font size used to render text.
  fontSize: 12

  # The font family used to render text.
  # If you need special characters support (i.e. powerline symbols),
  # keep 'mononoki' as a fallback (which has been patched to have those characters).
  # Valid values: any valid CSS font family list
  fontFamily: mononoki, monospace

  # The font weight used to render non-bold text.
  # Valid values: any valid CSS font weight
  fontWeight: normal

  # The font weight used to render bold text.
  # Valid values: any valid CSS font weight
  fontWeightBold: normal

  # The spacing in whole pixels between characters..
  letterSpacing: 1

  # The line height used to render text.
  lineHeight: 1

  # Whether to treat option as the meta key.
  # Valid values: true, false
  macOptionIsMeta: false

  # Whether holding a modifier key will force normal selection behavior,
  # regardless of whether the terminal is in mouse events mode. This will
  # also prevent mouse events from being emitted by the terminal. For example,
  # this allows you to use xterm.js' regular selection inside tmux with
  # mouse mode enabled.
  # Valid values: true, false
  macOptionClickForcesSelection: false

  # The type of renderer to use, this allows using the fallback DOM renderer
  # when canvas is too slow for the environment. The following features do
  # not work when the DOM renderer is used:
  #
  # - Line height
  # - Letter spacing
  # - Cursor blink
  # Valid values: dom, canvas
  rendererType: canvas

  # Whether to select the word under the cursor on right click, this is
  # standard behavior in a lot of macOS applications.
  # Valid values: true, false
  rightClickSelectsWord: false

  # Whether screen reader support is enabled. When on this will expose
  # supporting elements in the DOM to support NVDA on Windows and VoiceOver
  # on macOS.
  # Valid values: true, false
  screenReaderMode: false

  # The amount of scrollback in the terminal. Scrollback is the amount of rows
  # that are retained when lines are scrolled beyond the initial viewport.
  scrollback: 1000

  # The size of tab stops in the terminal.
  tabStopWidth: 4

  # The color theme of the terminal.
  # Valid values: any CSS colors
  theme:
    # The default foreground color
    foreground: "#FFF"

    # The default background color
    background: "#000"

    # The cursor color
    cursor: "#F80"

    # The accent color of the cursor (used as the foreground color for a block cursor)
    cursorAccent: "#F80"

    # The selection color (can be transparent)
    selection: "rgba(255,255,255,0.75)"

    # ANSI black (eg. `\x1b[30m`)
    black: "#111"

    # ANSI red (eg. `\x1b[31m`)
    red: "#F40"

    # ANSI green (eg. `\x1b[32m`)
    green: "#0F4"

    # ANSI yellow (eg. `\x1b[33m`)
    yellow: "#FC0"

    # ANSI blue (eg. `\x1b[34m`)
    blue: "#08F"

    # ANSI magenta (eg. `\x1b[35m`)
    magenta: "#80F"

    # ANSI cyan (eg. `\x1b[36m`)
    cyan: "#0F8"

    # ANSI white (eg. `\x1b[37m`)
    white: "#CCC"

    # ANSI bright black (eg. `\x1b[1;30m`)
    brightBlack: "#888"

    # ANSI bright red (eg. `\x1b[1;31m`)
    brightRed: "#F04"

    # ANSI bright green (eg. `\x1b[1;32m`)
    brightGreen: "#8F0"

    # ANSI bright yellow (eg. `\x1b[1;33m`)
    brightYellow: "#FF8"

    # ANSI bright blue (eg. `\x1b[1;34m`)
    brightBlue: "#44F"

    # ANSI bright magenta (eg. `\x1b[1;35m`)
    brightMagenta: "#F8C"

    # ANSI bright cyan (eg. `\x1b[1;36m`)
    brightCyan: "#4FC"

    # ANSI bright white (eg. `\x1b[1;37m`)
    brightWhite: "#FFF"

misc:
    # Initial size when the first terminal is opened
    initialCols: 80 # default: 80
    initialRows: 25 # default: 25

    # Enable vibrancy (blurry transparent window background)
    # Experimental feature, may have bugs and not work as expected.
    # Also you need to set the background color to transparent or semi-transparent
    # to make this work.
    vibrancy: false # default: false
    # Enable transparent window
    # In some cases vibrancy require this to be enabled.
    # This option only applies to new windows.
    transparent: false # default: false

    # Enables experimental WebGL renderer on xtermjs.
    # This option do not affect currently opening terminals.
    webGL: false # default: false

# Mod files (*.js), will be loaded into all windows when the config file load/reloads
# The load path is relative to $relative_path
mods:
  #- ./mod.js
